### ISSUE TITLE
The latest image (0.2.9) can not access certificates from NginxProxyManager anymore

### ISSUE THREAD

**Issue by pattisonmichael** [hassio-addons/addon-emqx#47]
# Problem/Motivation

EMQX doesn't start anymore due to unable to access the cert files.

## Expected behavior

It will start and read the file the same as previous version (0.2.8i).

## Actual behavior

It crashes and the emqx is shutting down

## Steps to reproduce
Configure SSL by putting this in the config. This works fine in 0.2.8

`- name: EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__CERTFILE`
`  value: ssl/nginxproxymanager/live/npm-3/fullchain.pem`
`- name: EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__KEYFILE`
`  value: ssl/nginxproxymanager/live/npm-3/privkey.pem`

Upgrade to latest version (0.2.9)

**Comment by spencerw67** [comment]
+1

**Comment by frenck** [comment]
```yaml
- name: EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__CERTFILE
  value: ssl/nginxproxymanager/live/npm-3/fullchain.pem
- name: EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__KEYFILE
  value: ssl/nginxproxymanager/live/npm-3/privkey.pem
```

There seems to be a prefix slash missing? `ssl/` -> `/ssl/` ?
You should be using a full path.

../Frenck
